# Generated by Django 5.0.7 on 2024-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_basemodel_cart_created_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Pizza',
            new_name='pizza',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
