# Generated by Django 5.2.8 on 2025-11-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pizza_cartitems_pizza_alter_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='pizza',
            new_name='Pizza',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
